spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:   # 路由队则
        - id: baidu_route    # 唯一id
          uri: https://www.baidu.com   # 满足断言后的目标url
          predicates:   # 配置断言
            - Query=url,baidu # 参数为baidu就跳转到目标url

        - id: qq_route    # 唯一id
          uri: https://www.qq.com   # 满足断言后的目标url
          predicates: # 配置断言
            - Query=url,qq  # 参数为qq就跳转到目标url

        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


# 前端项目中带有api前缀的默认路由到此
  application:
    name: mall-gateway
server:
  port: 88
